services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - progresDB:/data/postgres
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
  nest-api:
    image: nest-api
    container_name: nest-api
    restart: always
    ports:
      - 7000:7000
    depends_on:
      - postgres
    env_file:
      - .env
volumes:
  progresDB:
